# Generated by Django 3.2.6 on 2021-10-07 11:28

from django.db import migrations, models
import todolistclassviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('todolistclassviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='token',
            field=models.CharField(default=todolistclassviews.models.get_rendom_str, editable=False, max_length=32),
        ),
    ]
