# Generated by Django 3.2.6 on 2021-10-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolistclassviews', '0003_alter_itemmodel_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='is_shared',
            field=models.BooleanField(null=True, verbose_name=False),
        ),
    ]
