# Generated by Django 3.2.6 on 2021-10-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolistclassviews', '0004_itemmodel_is_shared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='is_shared',
            field=models.BooleanField(default=False, null=True, verbose_name='Teilen'),
        ),
    ]
